version: "3.3"

services:
  traefik:
    image: traefik:v2.2
    container_name: traefik
    networks:
      - traefik-public
      - internal
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - ${CERTS_LOCATION:-./crt}:/etc/certs
      - ./traefik/dynamic:/etc/traefik/dynamic

  mainpage:
    image: kamilwronka7/csgoed-mainpage:latest
    container_name: mainpage
    expose: [80]
    networks:
      - internal
    environment:
      - MAINPAGE_PORT
      - MAINPAGE_API_URL
    deploy:
      replicas: 5
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.mainpage.rule=Host(`csgoed.com`)"
        - "traefik.http.services.mainpage.loadbalancer.server.port=80"
        - "traefik.http.routers.mainpage.entrypoints=web,websecure"
        - "traefik.http.routers.mainpage.tls=true"

  mainpage-cms:
    image: kamilwronka7/csgoed-mainpage-cms:latest
    container_name: mainpage-cms
    expose: [80]
    networks:
      - internal
    environment:
      - CMS_PORT
      - CMS_DATABASE_HOST
      - CMS_DATABASE_NAME
      - CMS_DATABASE_PORT
      - CMS_HOST
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.mainpage-cms.rule=Host(`admin.csgoed.com`)"
        - "traefik.http.services.mainpage-cms.loadbalancer.server.port=80"
        - "traefik.http.routers.mainpage-cms.entrypoints=web,websecure"
        - "traefik.http.routers.mainpage-cms.tls=true"

  cms-db:
    image: bitnami/mongodb:4.2-debian-10
    container_name: cms-db
    networks:
      - internal
    deploy:
      replicas: 1

  backend-db:
    image: bitnami/mongodb:4.2-debian-10
    container_name: backend-db
    networks:
      - internal
    deploy:
      replicas: 1

  dashboard:
    image: kamilwronka7/csgoed-frontend:latest
    container_name: dashboard
    networks:
      - internal
    deploy:
      replicas: 5
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.dashboard.rule=Host(`dashboard.csgoed.com`)"
        - "traefik.http.services.dashboard.loadbalancer.server.port=80"
        - "traefik.http.routers.dashboard.entrypoints=web,websecure"
        - "traefik.http.routers.dashboard.tls=true"

  api:
    image: kamilwronka7/csgoed-backend:latest
    container_name: api
    expose: [80]
    networks:
      - internal
      # - traefik-public
    environment:
      - PORT=${API_PORT}
      - PAGE_URL
      - DASHBOARD_URL
      - DOMAIN_NAME
      - MAILGUN_DOMAIN
      - MAILGUN_API_KEY
      - MAILGUN_HOST
      - MONGODB_URI
      - STRIPE_PUBLISHABLE_KEY
      - STRIPE_SECRET_KEY
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.api.rule=Host(`api.csgoed.com`)"
        - "traefik.http.services.api.loadbalancer.server.port=80"
        - "traefik.http.routers.api.entrypoints=web,websecure"
        - "traefik.http.routers.api.tls=true"
      replicas: 10

networks:
  internal:
    driver: overlay
    external: false
  traefik-public:
    driver: overlay
    external: true
