version: "3.3"

services:
  traefik:
    image: traefik:v2.2
    container_name: traefik
    networks:
      # - traefik-public
      - internal
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./crt:/etc/certs
      - ./traefik/dynamic:/etc/traefik/dynamic

  mainpage:
    image: kamilwronka7/csgoed-mainpage:latest
    container_name: mainpage
    # expose: [80]
    networks:
      - internal
    environment:
      - MAINPAGE_PORT=80
      - MAINPAGE_API_URL=http://mainpage-cms:80
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.http.routers.mainpage.rule=Host(`csgoed.test`)"
      - "traefik.services.mainpage.loadbalancer.server.port=80"
      - "traefik.http.routers.mainpage.entrypoints=web,websecure"
      - "traefik.http.routers.mainpage.tls=true"
    deploy:
      replicas: 5

  mainpage-cms:
    image: kamilwronka7/csgoed-mainpage-cms:latest
    container_name: mainpage-cms
    # expose: [80]
    networks:
      - internal
    environment:
      - CMS_PORT=80
      - CMS_DATABASE_HOST=cms-db
      - CMS_DATABASE_NAME=csgoed
      - CMS_DATABASE_PORT=27017
      - CMS_HOST=0.0.0.0
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.http.routers.mainpage-cms.rule=Host(`admin.csgoed.test`)"
      - "traefik.http.services.mainpage.loadbalancer.server.port=80"
      - "traefik.http.routers.mainpage-cms.entrypoints=web,websecure"
      - "traefik.http.routers.mainpage-cms.tls=true"
    deploy:
      replicas: 1

  cms-db:
    image: bitnami/mongodb:4.2-debian-10
    container_name: cms-db
    networks:
      - internal
    deploy:
      replicas: 1

  backend-db:
    image: bitnami/mongodb:4.2-debian-10
    container_name: backend-db
    networks:
      - internal
    logging:
      driver: none
    deploy:
      replicas: 1

  dashboard:
    image: kamilwronka7/csgoed-frontend:latest
    container_name: dashboard
    networks:
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.http.routers.dashboard.rule=Host(`dashboard.csgoed.test`)"
      - "traefik.http.services.dashboard.loadbalancer.server.port=80"
      - "traefik.http.routers.dashboard.entrypoints=web,websecure"
      - "traefik.http.routers.dashboard.tls=true"
    deploy:
      replicas: 5

  api:
    image: kamilwronka7/csgoed-backend:latest
    container_name: api
    # expose: [80]
    environment:
      - PORT=80
      - PAGE_URL
      - DASHBOARD_URL
      - DOMAIN_NAME
      - MAILGUN_DOMAIN
      - MAILGUN_API_KEY
      - MAILGUN_HOST
      - MONGODB_URI
      - STRIPE_PUBLISHABLE_KEY
      - STRIPE_SECRET_KEY
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.http.routers.api.rule=Host(`api.csgoed.test`)"
      - "traefik.http.services.api.loadbalancer.server.port=80"
      - "traefik.http.routers.api.entrypoints=web,websecure"
      - "traefik.http.routers.api.tls=true"
    deploy:
      replicas: 8

networks:
  internal:
    # driver: overlay
    external: false
  traefik-public:
    external: true
