# log:
#   level: DEBUG

defaultEntryPoints:
  - web
  - websecure

providers:
  docker:
    swarmMode: true
    endpoint: "tcp://192.168.8.130:2376"
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

entrypoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: "https"
  websecure:
    address: :443

api:
  insecure: true
